djangosched/courses/urls.py
from django.conf.urls import url
from django.urls import include, path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'courses'

urlpatterns = [
    url(r'^$', views.course_list, name = 'list'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.edit_course, name = 'edit_course'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.course_delete, name = 'delete'),
    url(r'^create/$', views.course_create, name = 'create'),
    path('user/<prof>/', views.prof_course_list, name = 'prof'),
    url(r'^(?P<slug>[\w-]+)/$', views.course_details, name = 'detail'),
    url(r'^ready_page$', views.ready_page, name='ready_page'),
    url(r'^ready_page/apply_algo$', views.apply_algo, name = 'apply_algo'),
    url(r'^heiser_map$', views.heiser_map, name = 'heiser_map'),
    url(r'^ace_map$', views.ace_map, name = 'ace_map'),
]

urlpatterns += staticfiles_urlpatterns()

djangosched/djangosched/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from courses import views as course_views
from home import views as home_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', views.about),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

djangosched/home/urls.py
from django.conf.urls import url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'home'

urlpatterns = [
    url(r'^$', views.home_view, name = 'home-page'),
    ]

urlpatterns += staticfiles_urlpatterns()

djangosched/home/models.py
from django.db import models

# Create your models here.

djangosched/home/views.py
from django.shortcuts import render
from courses.models import Course
from courses.forms import forms
from courses.views import translate_back
from arbiter.artime import TimePref

# Create your views here.
def home_view(request):
	courses = Course.objects.all().order_by('date')
	courses = sorted(courses, key=lambda course:translate_back(course.assigned_time).toord())
	return render(request, 'home/home_page.html', {'courses':courses})

djangosched/home/templates/home/home_page.html
{% extends 'base_html.html' %}

{% load static from staticfiles %}

{% block content %}
	<head>
		<meta charset = "utf-8">
		<title>Home Page</title>
		<link rel = "stylesheet" href="{% static 'styles.css' %}">
	</head>

	<body>

		{% if user.is_authenticated %}

		<h1>Welcome {{user.first_name}} {{user.last_name}}!!!</h1>

		<p>Here are your classes:</p>

		<div class = "courses">
			{% for course in courses %}
				{% if course.professor == user %}
				<div class = "course">
					{% if not course.has_conflict %}
						<h2><a href = "{% url 'courses:detail' slug=course.slug %}">{{course.title}}</a></h2>
					{% else %}
						<h2><a href = "{% url 'courses:detail' slug=course.slug %}" style ="color: red">*{{course.title}}*</a></h2>
					{% endif %}
					<p>{{course.snippet}}</p>
					<p>{{course.assigned_room}}</p>
					<p>{{course.assigned_time}}</p>
					<p class = "professor">Taught by {{user.first_name}} {{user.last_name}}</p>
				</div>
				{% endif %}
			{% endfor %}
		</div>

		{% else %}

		<h1>Welcome to the New College Course Scheduler</h1>
		<p>Please sign up or Login to view or add courses</p>
		{% endif %}

	</body>

{% endblock %}