djangosched/courses/urls.py
from django.conf.urls import url
from django.urls import include, path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'courses'

urlpatterns = [
    url(r'^$', views.course_list, name = 'list'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.edit_course, name = 'edit_course'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.course_delete, name = 'delete'),
    url(r'^create/$', views.course_create, name = 'create'),
    path('user/<prof>/', views.prof_course_list, name = 'prof'),
    url(r'^(?P<slug>[\w-]+)/$', views.course_details, name = 'detail'),
    url(r'^ready_page$', views.ready_page, name='ready_page'),
    url(r'^ready_page/apply_algo$', views.apply_algo, name = 'apply_algo'),
    url(r'^heiser_map$', views.heiser_map, name = 'heiser_map'),
    url(r'^ace_map$', views.ace_map, name = 'ace_map'),
]

urlpatterns += staticfiles_urlpatterns()

djangosched/djangosched/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from courses import views as course_views
from home import views as home_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', views.about),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

djangosched/home/urls.py
from django.conf.urls import url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'home'

urlpatterns = [
    url(r'^$', views.home_view, name = 'home-page'),
    ]

urlpatterns += staticfiles_urlpatterns()

djangosched/courses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from courses.choices import *
from django.core.validators import MaxValueValidator

# possibly make more tables and use joins to make them save room and easier to access for the individual professor, room, ect. view
# Create your models here.
class Course(models.Model):
	title = models.CharField(max_length = 100)
	decription = models.TextField()
	department = models.CharField(choices = DEPT_CHOICES, max_length = 30)
	level = models.CharField(choices = LEVEL_CHOICES, max_length = 20)
	ucs_time_date1 = models.CharField(choices = UCS_TIME_CHOICES, max_length = 10)
	ucs_time_date2 = models.CharField(choices = UCS_TIME_CHOICES, max_length = 10)
	ucs_time_date3 = models.CharField(choices = UCS_TIME_CHOICES, max_length = 10)
	slug = models.SlugField()
	date = models.DateTimeField(auto_now_add = True)
	professor = models.ForeignKey(User, default = None, on_delete = True)
	room1 = models.CharField(choices = ROOM_CHOICES, max_length = 20)
	room2 = models.CharField(choices = ROOM_CHOICES, max_length = 20)
	room3 = models.CharField(choices = ROOM_CHOICES, max_length = 20)
	assigned_room = models.CharField(max_length = 20)
	assigned_time = models.CharField(max_length = 100)
	has_conflict = models.BooleanField(default = False)
	enemies = models.CharField(max_length = 3000, default = "")
	cap = models.IntegerField(default = 0, validators=[MaxValueValidator(85)])
	prerequisite = models.CharField(max_length = 300, blank=True)
	term_length = models.CharField(choices = TERM_CHOICES, max_length = 30)
	LAC = models.BooleanField(default = False)
	Gender_Studies = models.BooleanField(default = False)
	Interdisciplinary = models.BooleanField(default = False)

	def __str__(self):
		return self.title

	def snippet(self):
		return self.decription[:50] + '...'

djangosched/courses/forms.py
from django import forms
from . import models
from courses.choices import *

class CreateCourse(forms.ModelForm):
	class Meta:
		model = models.Course
		fields = ['title', 'department', 'level', 'decription', 'ucs_time_date1', 'ucs_time_date2', 'ucs_time_date3', 'room1', 'room2', 'room3', 'cap', 'term_length', 'prerequisite', 'LAC', 'Gender_Studies', 'Interdisciplinary']

		labels = {'decription':'Description',
				  'ucs_time_date1':'First Choice Time',
				  'ucs_time_date2':'Second Choice Time',
				  'ucs_time_date3':'Third Choice Time',
				  'room1':'First Choice Room',
				  'room2':'Second Choice Room',
				  'room3':'Third Choice Room',
				  'cap':'Max Number of Students',
				  'prerequisite':'Prerequisites',
				  }
		#will add more in depth, specific fields of different types to make it easier to
		#input time and day options.





class FilterCourseList(forms.Form):
	instructor = forms.ModelChoiceField(label='Instructor:', queryset=models.User.objects.all().order_by('username'), required=False)
	dept = forms.ChoiceField(label='Department:', choices=DEPT_CHOICES, required=False)
	time = forms.ChoiceField(label='Time:', choices=UCS_TIME_CHOICES, required=False)
	room = forms.ChoiceField(label='Location:', choices=ROOM_CHOICES, required=False)

djangosched/courses/views.py
from django.shortcuts import render, redirect
from .models import Course
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
from arbiter.ucs import codes
from arbiter.sched import get_solution
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from arbiter.artime import *
from .forms import CreateCourse
from django.core.exceptions import PermissionDenied

def heiser_map(request):
	return render(request, 'courses/heisermap.html')

def ace_map(request):
	return render(request, 'courses/acemap.html')

def ready_page(request):
	if not request.user.is_superuser:
		return redirect('home:home-page')

	return render(request, 'courses/ready_page.html')

def apply_algo(request):
	if not request.user.is_superuser:
		return redirect('home:home-page')
	courses = Course.objects.all().order_by('date')
	d = {}
	for course in courses:
		d[course.id] = {'time':set([codes[course.ucs_time_date1], codes[course.ucs_time_date2], codes[course.ucs_time_date3],]),
						'room':set([course.room1, course.room2, course.room3]),
						'prof':course.professor,
						'dept':course.department,
						'level':course.level,
						'name':course.title}

	solution = get_solution(d)

	if solution != 'FAILURE':
		for course_id in solution:
			course = Course.objects.get(id = course_id)
			course.assigned_room = solution[course_id]['room']
			course.assigned_time = str(solution[course_id]['time'])
			course.has_conflict = solution[course_id]['conflict']
			course.enemies = solution[course_id]['enemies']
			course.save()
		print(len(Course.objects.filter(has_conflict=True)), "conflicts")
	else:
		print('Arbiter Failed')

	return redirect('courses:list')


def translate_back(s):
	for code in codes:
		if str(codes[code]) == s:
			return codes[code]
	return TimePref([TimeSlot(WeekTime(0,0,1), WeekTime(0,0,2))])

# Create your views here.
@login_required(login_url = "/accounts/login/")
def course_list(request):
	courses = Course.objects.all()
	if request.method == "POST":
		form = forms.FilterCourseList(request.POST, request.FILES)
		if form.is_valid():
			instructor = form.cleaned_data.get('instructor')
			if instructor:
				courses = courses.filter(professor=User.objects.get(username=instructor))
			dept = form.cleaned_data.get('dept')
			if dept:
				courses = courses.filter(department=dept)
			time = form.cleaned_data.get('time')
			if time:
				courses = courses.filter(assigned_time=str(codes[time]))
			room = form.cleaned_data.get('room')
			if room:
				courses = courses.filter(assigned_room=room)
	else:
		form = forms.FilterCourseList()

	courses = sorted(courses, key=lambda course:translate_back(course.assigned_time).toord())

	return render(request, 'courses/course_list.html', {'courses':courses, 'form':form})

@login_required(login_url = "/accounts/login/")
def prof_course_list(request, prof):
	courses = Course.objects.filter(professor=User.objects.get(username=prof))
	courses = sorted(courses, key=lambda course:translate_back(course.assigned_time).toord())
	form = forms.FilterCourseList()

	return render(request, 'courses/course_list.html', {'courses':courses, 'form':form})

@login_required(login_url = "/accounts/login/")
def course_details(request, slug):
	# return HttpResponse("This is where the description will be")
	course = Course.objects.get(slug = slug)
	return render(request, 'courses/course_detail.html', {'course':course})

@login_required(login_url="/accounts/login/")
def course_create(request):
	if request.method == "POST":
		form = forms.CreateCourse(request.POST, request.FILES)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.professor = request.user
			instance.slug = slugify(request.POST.get("title", ""))
			instance.save()
			return redirect('courses:list')
	else:
		form = forms.CreateCourse()
	return render(request, 'courses/course_create.html', {'form':form})

@login_required(login_url = "/accounts/login/")
def edit_course(request, slug):
	instance = Course.objects.get(slug=slug)

	if request.user != instance.professor and not request.user.is_superuser:
		return redirect('courses:detail', slug=instance.slug)

	if request.method == "POST":
		form = forms.CreateCourse(request.POST, instance=instance)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.slug = slugify(request.POST.get("title", ""))
			instance.save()
			return redirect('courses:detail', slug=instance.slug)
	else:
		form = forms.CreateCourse(instance = instance)

	context = {
		'form':form,
		'course':instance
	}
	return render(request, 'courses/edit_course.html', context)

@login_required(login_url = "/accounts/login/")
def course_delete(request, slug):
	instance = Course.objects.get(slug=slug)

	if request.user != instance.professor and not request.user.is_superuser:
		return redirect('courses:detail', slug=instance.slug)

	if request.user == instance.professor:
		instance.delete()
		return redirect('courses:list')
	else:
		return redirect('courses:detail', slug=instance.slug)

djangosched/courses/templates/courses/acemap.html
{% extends 'base_html.html' %}

{% load static from staticfiles %}

{% block content %}
	<head>
		<meta charset = "utf-8">
		<title>Ready Page</title>
		<link rel = "stylesheet" href="{% static 'styles.css' %}">
	</head>

  <body>
    <div class = "map">
      <h3> ACE 1st Floor</h3>
      <img src="{% static 'ace1.png' %}"/>
      <h3> ACE 2st Floor</h3>
      <img src="{% static 'ace2.png' %}"/>
      <h3> ACE 3st Floor</h3>
      <img src="{% static 'ACE3.png' %}"/>
    </div>
  </body>

  {% endblock %}

djangosched/courses/templates/courses/course_create.html
{% extends 'base_html.html' %}

{% load static from staticfiles %}

{% block content %}
<head>
	<meta charset = "utf-8">
	<title>Course</title>
	<link rel = "stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
		<a href="{% url 'courses:heiser_map' %}" target="_blank" class = "mapButtons">Heiser Layout</a>
		<a href="{% url 'courses:ace_map' %}" target="_blank" class = "mapButtons">Ace Layout</a>
	<div class= "create-course">
		<form class='site-form' action = '{% url "courses:create" %}' method = 'post'>
			{% csrf_token %}
			{{ form }}
			<input type= "submit" value="Create">
		</form>
	</div>
</body>

{% endblock %}

djangosched/courses/templates/courses/course_delete.html
{% extends 'base_html.html' %}

{% load static from staticfiles %}

{% block content %}
<head>
	<meta charset = "utf-8">
	<link rel = "stylesheet" href="{% static 'styles.css' %}">
		<title>Delete Course</title>
			<div class = "edit-course">
				<h2>Delete Course</h2>
				<form class = 'site-form' method = 'post'>
					<input type = "submit" value = "Delete">
					{% csrf_token %}
					{{form}}
				</form>
			</div>
	<script src="/static/slugify.js"></script>
{% endblock %}

djangosched/courses/templates/courses/course_detail.html
{% extends 'base_html.html' %}

{% load static from staticfiles %}

{% block content %}
<head>
	<meta charset = "utf-8">
	<title>Course</title>
	<link rel = "stylesheet" href="{% static 'styles.css' %}">
	{% if user.is_superuser or user == course.professor %}
		<td><a href="{% url 'courses:edit_course' slug=course.slug %}"><button type="button" class="btn btn-warning">Edit</button></a></td>
		<td><a href="{% url 'courses:delete' slug=course.slug %}"><button type="submit" class="btn btn-warning">Delete</button></a></td>
	{% endif %}
</head>
<div class= "course-detail">
	<div class = "course">
		{% if not course.has_conflict %}
			<h2>{{course.title}}</h2>
		{% else %}
			<h2 style="color: red">*{{course.title}}*</h2>
		{% endif %}
		<p>Description:{{course.decription}}</p>
		<p>Prereqs:{{course.prerequisite}}</p>
		<p>Time:{{course.assigned_time}}</p><p>Room:{{course.assigned_room}}</p>
		<p>Length:{{course.term_length}}</p><p>Cap:{{course.cap}}</p>
		<p class = "professor">Taught by {{course.professor}}</p>
		{% if course.enemies != "" %}
			<p style="color: red">This course conflicts with:<br>{{course.enemies |safe}}</p>
		{% endif %}
	</div>
</div>
{% endblock %}

djangosched/courses/templates/courses/course_edit.html
{% extends 'base_html.html' %}

{% load static from staticfiles %}

{% block content %}
<head>
	<meta charset = "utf-8">
	<link rel = "stylesheet" href="{% static 'styles.css' %}">
		<title>Edit Course</title>
			<div class = "edit-course">
				<h2>Edit Course</h2>
				{{form}}
				<form class = 'site-form' action = '{% url "courses:detail" %}' method = 'post'>
				<input type = "submit" value = "Save">
				</form>
			</div>
	<script src="/static/slugify.js"></script>
{% endblock %}

djangosched/courses/templates/courses/course_list.html
{% extends 'base_html.html' %}

{% load static from staticfiles %}

{% block content %}
<head>
	<meta charset = "utf-8">
	<title>Course</title>
	<link rel = "stylesheet" href="{% static 'styles.css' %}">
		<h1>Courses</h1>
		<div class = searchForm>
			<form action= '{% url "courses:list" %}' method=post>
				{% csrf_token %}
				{{ form }}
				<input type='submit' value = 'Filter' class="button">
			</form>
		</div>
		<div class = "courses">
			{% for course in courses %}
				<div class = "course">
					{% if not course.has_conflict %}
						<h2><a href = "{% url 'courses:detail' slug=course.slug %}">{{course.title}}</a></h2>
					{% else %}
						<h2><a href = "{% url 'courses:detail' slug=course.slug %}" style ="color: red">*{{course.title}}*</a></h2>
					{% endif %}
					<p>{{course.snippet}}</p>
					<p>{{course.assigned_room}}</p>
					<p>{{course.assigned_time}}</p>
					<p class = "professor">Taught by {{course.professor}}</p>
				</div>
			{% endfor %}
		</div>
{% endblock %}

djangosched/courses/templates/courses/edit_course.html
{% extends 'base_html.html' %}

{% load static from staticfiles %}

{% block content %}
<head>
	<meta charset = "utf-8">
	<link rel = "stylesheet" href="{% static 'styles.css' %}">
		<title>Edit Course</title>
			<div class = "edit-course">
				<h2>Edit Course</h2>
				<form class = 'site-form' method = 'post'>
					{% csrf_token %}
					{{form}}
					<input type = "submit" value = "Save">
				</form>
			</div>
	<script src="/static/slugify.js"></script>
{% endblock %}

djangosched/courses/templates/courses/heisermap.html
{% extends 'base_html.html' %}

{% load static from staticfiles %}

{% block content %}
	<head>
		<meta charset = "utf-8">
		<title>Ready Page</title>
		<link rel = "stylesheet" href="{% static 'styles.css' %}">
	</head>

  <body>
    <div class = "map">
      <h3> Heiser 1st Floor</h3>
      <img src="{% static 'heiser1.png' %}"/>
    </div>
  </body>

  {% endblock %}

djangosched/courses/templates/courses/ready_page.html
{% extends 'base_html.html' %}

{% load static from staticfiles %}

{% block content %}
	<head>
		<meta charset = "utf-8">
		<title>Ready Page</title>
		<link rel = "stylesheet" href="{% static 'styles.css' %}">
	</head>

	<body>
    <div class = "ready_page">
      <p> The creation of the schedule can take a couple of minutes.
        Please don't close window, doing so will make schedule wonky.</p>
        <p> Once this button is pressed please wait until you are redirected to a new page.</p>
        <div class = "center">
          <a href = "{% url 'courses:apply_algo' %}" class="red" value="Creates Schedule">I understand, Create Schedule</a>
        </div>
    </div>
  </body>
{% endblock %}