djangosched/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'accounts'

urlpatterns = [
	url(r'^signup/$', views.signup_view, name = 'signup'),
	url(r'^login/$', views.login_view, name = 'login'),
	url(r'^logout/$', views.logout_view, name = 'logout')
]

urlpatterns += staticfiles_urlpatterns()

djangosched/courses/urls.py
from django.conf.urls import url
from django.urls import include, path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'courses'

urlpatterns = [
    url(r'^$', views.course_list, name = 'list'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.edit_course, name = 'edit_course'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.course_delete, name = 'delete'),
    url(r'^create/$', views.course_create, name = 'create'),
    path('user/<prof>/', views.prof_course_list, name = 'prof'),
    url(r'^(?P<slug>[\w-]+)/$', views.course_details, name = 'detail'),
    url(r'^ready_page$', views.ready_page, name='ready_page'),
    url(r'^ready_page/apply_algo$', views.apply_algo, name = 'apply_algo'),
    url(r'^heiser_map$', views.heiser_map, name = 'heiser_map'),
    url(r'^ace_map$', views.ace_map, name = 'ace_map'),
]

urlpatterns += staticfiles_urlpatterns()

djangosched/djangosched/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from courses import views as course_views
from home import views as home_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', views.about),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

djangosched/home/urls.py
from django.conf.urls import url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'home'

urlpatterns = [
    url(r'^$', views.home_view, name = 'home-page'),
    ]

urlpatterns += staticfiles_urlpatterns()

djangosched/templates/about.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset = "utf-8">
		<title>This is the about page</title>
	</head>
	<body>
		<h1>This is the about page</h1>
		<p>here you can find all the links you need to navigate</p>
	</body>
</html>

djangosched/templates/base_html.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset = "utf-8">
		<title>Scheduler</title>
		<link ref = "stylesheet" href = "{% static 'styles.css' %}">
	</head>

	<body>
		<header class="wrapper">
			<a href = "{% url 'home:home-page' %}" title="Home"><img src="{% static 'NewCollegeSmall.png' alt='Scheduler' %}"/></a>

            {% if user.is_superuser %}
                <nav>
                    <a href = "{% url 'home:home-page' %}" class="button">Home</a>
                    <a href = "{% url 'courses:list' %}" class="button">View Courses</a>
                    <a href="{% url 'courses:create' %}" class="button">New Course</a>
                    <a href = "{% url 'admin:index' %}" class="button">Admin Page</a>
                    <a href = "{% url 'courses:ready_page' %}" class="red" value="Creates Schedule">Create Schedule</a>
                    <form class = "logout" action= "{% url 'accounts:logout' %}" method = "post">
                    {% csrf_token %}
                    <button type="submit" class="button" value="Logout">Logout</button></form>
                </nav>
            {% endif %}

            {% if user.is_authenticated and not user.is_superuser%}
                <nav>
                    <a href = "{% url 'home:home-page' %}" class="button">Home</a>
                    <a href = "{% url 'courses:list' %}" class="button">View Courses</a>
                    <a href="{% url 'courses:create' %}" class="button">New Course</a>
                    <form class = "logout" action= "{% url 'accounts:logout' %}" method = "post">
                    {% csrf_token %}
                    <button type="submit" class="button" value="Logout">Logout</button></form>
                </nav>
            {% endif %}

            {% if not user.is_authenticated %}
                <nav>
                   <a href = "{% url 'accounts:login' %}" class="button">Login</a>
                   <a href = "{% url 'accounts:signup' %}" class="button">Signup</a>
                </nav>
            {% endif %}
		</header>

		<div class = "wrapper">
			{%block content%}
			{%endblock%}
		</div>

	</body>
</html>